[package]
name = "simp"
version = "3.3.0"
authors = ["Axel Kappel"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://simp.axelkappel.se"
description = "The simple image manipulation program"
repository = "https://github.com/Kl4rry/simp"
categories = ["multimedia::images", "multimedia::encoding"]
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.0"
cgmath = { version = "0.18.0", features = ["swizzle"] }
confy = "0.5.0"
ctrlc = "3.2.0"
directories = "4.0.1"
egui = "0.20.0"
egui_glium = "0.20.0"
fontdb = "0.10.0"
glium = "0.32.1"
image = { version = "0.24.2", features = ["exr"] }
imagepipe = "0.5.0"
lazy_static = "1.4.0"
libwebp = { version = "0.1.2", features = ["static"] }
lru = "0.8.1"
nanoid = "0.4.0"
num-traits = "0.2.15"
once_cell = "1.14.0"
psd = "0.3.3"
rawloader = "0.37.0"
resvg = "0.28.0"
rexif = "0.7.3"
rfd = "0.10.0"
serde = { version = "1", features = ["derive"] }
tiny-skia = "0.8.2"
trash = { version = "3.0", optional = true }
usvg = "0.28.0"
webbrowser = "0.8.0"
webp-animation = "0.7.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
winapi = { version = "0.3.9", features = ["everything"] }

[package.metadata.winres]
OriginalFilename = "simp.exe"
FileDescription = "Simp"
LegalCopyright = "Copyright © 2021 Axel Kappel"
ProductName = "Simp"

[profile.release]
lto = "thin"
strip = true

[profile.dev]
opt-level = 3

[features]
default = ["trash"]
avif = ["image/avif-decoder"]
