.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH simp 1  "simp 3.6.1" 
.SH NAME
simp \- The simple image manipulation program
.SH SYNOPSIS
\fBsimp\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIFILE\fR] 
.SH DESCRIPTION
The simple image manipulation program
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.TP
[\fIFILE\fR]
Load this file
.SH VERSION
v3.6.1
.SH AUTHORS
Axel Kappel
