name: Rust

on: [push]

jobs:
  vendor-sources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Vendor
        run: |
          mkdir -p .cargo
          cargo vendor > .cargo/config.toml
      - name: Package all sources
        run: tar -czvf simp-vendored-source.tar.gz *
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: vendored-source
          path: simp-vendored-source.tar.gz

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install snap deps
        run: sudo snap install dav1d

      - name: Install apt deps
        run: sudo apt update && sudo apt install libheif-dev

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Install cargo about
        run: cargo install cargo-about --features=cli --locked
      - name: Build
        run: cargo build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ubuntu-build-artifacts
          path: target/release/simp

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Install cargo about
        run: cargo install cargo-about --features=cli --locked
      - name: Build
        run: cargo build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: windows-build-artifacts
          path: target/release/simp.exe

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - name: Install cargo about
        run: cargo install cargo-about --features=cli --locked
      - name: Build
        run: cargo build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-build-artifacts
          path: target/release/simp
